# Starting Saves
# Each time a player falls into the void it gets counted until they reach the max amount of saves, If the player runs out of saves they simply die in the void.
starting_saves: "3"

# Saves Price
# The price of each save the players buy.
saves_price: "100"

# Enable All Worlds
# If true, the anti-void feature is enabled for all worlds, otherwise, the worlds array will be used.
enable_all_worlds: false

# Allowed Worlds
# Specify which worlds the anti void occurs.
worlds:
  - Hub
  - world
